default: &default  
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default  
  database: elastic_rails_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: elastic_rails_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>  

